import img from '../images/preload.png'
export const moviesData = [
  {
    _id: 1,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 2,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 3,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 4,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 5,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 6,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 7,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 8,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 9,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 10,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 11,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 12,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 13,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 14,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 15,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 16,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 17,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 18,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 19,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 20,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 21,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 22,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
]

export const saveMovies = [
  {
    _id: 5,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 6,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
  {
    _id: 7,
    name: '33 слова о дизайне',
    image: img,
    duration: "1ч 42м",
    link: "https://www.youtube.com/watch?v=iudeJyaOxss",
  },
]
